#!/bin/bash
while read -r file; do
    case "$1" in

    # Copy path to image
    "C-c")
        path=$(echo -n "$file" | sed "s@^\.@$PWD@")

        if [ -z  "$(echo -n "$path" | grep /)" ]; then
            path=$PWD/$path
        fi

        echo -n "$path" | xclip -selection clipboard ;;
    esac
done
